apiVersion: v1
kind: Service
metadata:
  name: fibloader
  labels:
    run: fibloader
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    component: fibloader
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibloader
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: fibloader
    spec:
      containers:
        - name: fib-web-loader
          image: johnlabarge/fib-web-loader
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 300Mi
          ports:
           - containerPort: 8080
          env:
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fibloader-autoscaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: fibloader
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 50

